### ISSUE TITLE
WriteZeroes

### ISSUE THREAD

**Issue by Alexey-T** [Akira13641/TLightFileStream#4]
Not sure, maybe such method is useful

Or WriteFill(n: byte; count: int)

**Comment by Akira13641** [comment]
I made it generic. The function signature looks like this:  
  
`function FillWith<T>(constref Value: T; const NumInstances: SizeUInt): PLightFileStream;`  
  
Added a part to the example that shows it, also.

**Comment by Alexey-T** [comment]
FillWith(0,n) is ambiguous , need byte version
