### ISSUE TITLE
const params

### ISSUE THREAD

**Issue by Alexey-T** [Akira13641/TLightFileStream#7]
>Why const x : byte ?  On some architectures that might be by ref.

**Comment by Akira13641** [comment]
The `Buffer` input parameter to both FileRead and FileWrite is a "formal const" anyways, so I don't think that this one ultimately matters. What architectures did you have in mind? Also note that `const` is not the same as `constref`.

**Comment by Alexey-T** [comment]
I read it at Lazarus forum, don’t know

**Comment by Akira13641** [comment]
I think I'll leave this one as it is, for the time being at least.
